name: Build and Deploy to project-showcase

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: npm ci && npm run build

      - run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git clone https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/danifernao/project-showcase.git

      - run: |
          rm -rf project-showcase/stopwatch
          mkdir -p project-showcase/stopwatch
          cp -r dist/* project-showcase/stopwatch/

      - run: |
          cd project-showcase
          git add .
          git commit -m "Actualiza carpeta 'stopwatch' desde repositorio 'stopwatch'" || echo "No hay cambios para registrar"
          git push
